### PR TITLE
ci: fix semantic-release

### LINKED ISSUE #53: Add semantic-bot
Missing:

image

### PR DESCRIPTION
**Pull request by Zxilly**
fix: #53 
refer to: https://github.com/node-casbin/sequelize-adapter/runs/3087855699?check_suite_focus=true
@hsluoyz plz review
Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Zxilly there's no semantic-bot:

image

**Comment by Zxilly** [comment]
@hsluoyz bot was used to confirm a issue or pull request has been included in a release.
It will appear if a successful release was executed.

**Comment by Zxilly** [comment]
image
release step is skipped in the pull request action

**Comment by hsluoyz** [comment]
@Zxilly I mean this one: https://github.com/casbin/casbin/pull/838 to check the commit message format

image

**Comment by Zxilly** [comment]
@hsluoyz I got it. working on this

**Comment by Zxilly** [comment]
@hsluoyz now bot works

**Pull request merged**
