### PR TITLE
update deps & add prettier & replace tslint with eslint

### PR DESCRIPTION
**Pull request by zhmushan**
TSLint has been deprecated as of 2019

### CODE REVIEW

**Comment by zhmushan** [comment]
@nodece 8.x has been outdated for too long, Nodejs is different from browsers, we don’t need to be compatible with the obsolete version. What do you think?

**Comment by nodece** [comment]
@zhmushan Could remove node8 from travis-ci?

**Comment by zhmushan** [comment]
@nodece I prefer to use Github Actions directly (if you agree

**Comment by nodece** [comment]
@zhmushan I agreed use GitHub Actions.

**Comment by zhmushan** [comment]
@nodece Trivis removal will continue in the next pr, I need to try how to use coveralls in GitHub Actions

**Pull request merged**
