### PR TITLE
changed the version of sequelize to 6.3.5

### LINKED ISSUE #34: how long to start support v6
how long to start support v6

### PR DESCRIPTION
**Pull request by the-good-boy**
Fix: https://github.com/node-casbin/sequelize-adapter/issues/34

### CODE REVIEW

**Comment by hsluoyz** [comment]
@the-good-boy plz fix CI.

**Comment by hsluoyz** [comment]
@zhmushan do you have any idea for this?

**Comment by zhmushan** [comment]
We need to wait for "sequelize-typescript" to release 2.0.0

**Comment by hsluoyz** [comment]
OK. Closed for now.

**Pull request closed without merging**
