### PR TITLE
feat: add support for custom table name

### LINKED ISSUE #43: Add support for custom table name
Hi, thanks for this library ❤️ 

Would it be possible to support changing the default `casbin_rule` table name? We have our own convention of table names and at the moment `casbin_rule` sticks out.

I'm thinking of something like:
```ts
const adapter = await SequelizeAdapter.newAdapter({
    username: config.db.username,
    // ...
    tableName: 'not_casbin_rule`
});
```

Happy to make a PR for it.

### PR DESCRIPTION
**Pull request by Zxilly**
Fix: https://github.com/node-casbin/sequelize-adapter/issues/43

@Gabriel-403 @hsluoyz @nodece plz review
Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Zxilly plz finish: https://github.com/node-casbin/sequelize-adapter/issues/47 first

**Comment by Gabriel-403** [comment]
> @Zxilly plz finish: #47 first

I am woking on this,this is my task

**Review by nodece — APPROVED** [review]
LGTM

**Comment by hsluoyz** [comment]
@Zxilly plz fix:

image

**Comment by Zxilly** [comment]
@hsluoyz resolved

**Pull request merged**
